import { IgnoreFileType } from './types';

export const SUPPORTED_FILE_TYPES: Readonly<Record<string, IgnoreFileType>> = {
    '.gitignore': 'gitignore',
    '.prettierignore': 'gitignore',
    '.aiderignore': 'gitignore',
    '.aiexclude': 'gitignore',
    '.aiignore': 'gitignore',
    '.alexignore': 'gitignore',
    '.augmentignore': 'gitignore',
    '.bazelignore': 'gitignore',
    '.cfignore': 'gitignore',
    '.clineignore': 'gitignore',
    '.codeiumignore': 'gitignore',
    '.cursorignore': 'gitignore',
    '.deployignore': 'gitignore',
    '.distignore': 'gitignore',
    '.ebignore': 'gitignore',
    '.eleventyignore': 'gitignore',
    '.eslintignore': 'gitignore',
    '.flooignore': 'gitignore',
    '.geminiignore': 'gitignore',
    '.helmignore': 'gitignore',
    '.ignore': 'gitignore',
    '.jpmignore': 'gitignore',
    '.jshintignore': 'gitignore',
    '.markdownlintignore': 'gitignore',
    '.nodemonignore': 'gitignore',
    '.nuxtignore': 'gitignore',
    '.rgignore': 'gitignore',
    '.slugignore': 'gitignore',
    '.solhintignore': 'gitignore',
    '.stylelintignore': 'gitignore',
    '.stylintignore': 'gitignore',
    '.swagger-codegen-ignore': 'gitignore',
    '.tabnineignore': 'gitignore',
    '.terraformignore': 'gitignore',
    '.tokeignore': 'gitignore',
    '.upignore': 'gitignore',
    '.vercelignore': 'gitignore',
    '.yarnignore': 'gitignore',
    '.gcloudignore': 'vscodeignore',
    '.npmignore': 'vscodeignore',
    '.vscodeignore': 'vscodeignore',
    '.bzrignore': 'glob-no-negation',
    '.chefignore': 'glob-no-negation',
    '.tfignore': 'tfignore',
    '.dockerignore': 'dockerignore',
    '.cvsignore': 'cvsignore',
    '.p4ignore': 'p4ignore'
};

export const ALL_SUPPORTED_FILES: readonly string[] = Object.keys(SUPPORTED_FILE_TYPES);
